// Jenkinsfile testing test
pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'python:2-alpine'
                }
            }
            steps {
                sh 'python -m py_compile project/2_DevLab/experiment_rfor/score.py'
            }
        }
        stage('Code quality test') {
            agent { 
                // dockerfile {
                //     filename 'Dockerfile'
                //     dir 'project/3_CI_CD/code_quality_test'
                // }             
                docker {
                    image 'in92/devops_pylint:v1.0' 
                }  
            }
            steps {
                withEnv(['PYLINTHOME=.']) {
                    sh 'pylint project/2_DevLab/experiment_rfor/score.py'
                }
                sh "python -c 'import sys,json; json.load(sys.stdin)' < file.json"
            }
        }
    }
}