// Jenkinsfile testing test
pipeline {
    agent none
    stages {

        stage('Code Quality Test') {

            parallel{

                    stage('Score Code Quality Test') {

                        agent {
                            docker {
                                image 'in92/devops_pylint:v1.3' 
                            }
                        }

                        steps{
                            sh 'pylint --disable=C,R,W project/2_DevLab/experiment_rfor/score.py'
                        }
                    }

                    stage('Train Code Quality Test') {

                        agent {
                            docker {
                                image 'in92/devops_pylint:v1.3' 
                            }
                        }

                        steps{
                            sh 'pylint --disable=C project/2_DevLab/experiment_rfor/train.py'
                        }
                    }

                }

            post {

                success {
                        echo 'Score and Train code files successfully passed the Code Quality Test!'
                    }

                failure {
                        echo 'Code failed the quality test, please see logs.'
                    }
            }
        }

        stage('Code Validation Test') {

            parallel {

                stage('Validate Train Code') {

                    agent {
                        docker {
                            image 'python:3-alpine' 
                        }
                    }

                    steps {
                        sh 'python -m py_compile project/2_DevLab/experiment_rfor/train.py'
                    }
                }

                stage('Validate Score Code') {

                    agent {
                        docker {
                            image 'python:3-alpine' 
                        }
                    }

                    steps {
                        sh 'python -m py_compile project/2_DevLab/experiment_rfor/score.py'
                    }
                }
            }

            post {

                success {
                        echo 'Score and Train code files successfully validated!'
                    }

                failure {
                        echo 'Code failed the Validation test, please see logs.'
                    }
            }
        }

        stage('Unit test') {

            agent {
                docker {
                    image 'in92/devops_pyunit:v1.0' 
                    }
            }

            steps {
                sh 'python project/3_CI_CD/3_unit_test/unit_test_rforpipeline.py ./experiment_rfor/rfor_pipeline.pickle test.csv result.csv'
            }
        }

        stage('Model MetaData Quality Test') {

            parallel {

                stage('Validate inputVar.json file') {

                    agent {
                        docker {
                            image 'python:3-alpine' 
                        }
                    }

                    steps {
                        sh "python -c 'import sys,json; json.load(sys.stdin)' < project/2_DevLab/experiment_rfor/inputVar.json"
                    }
                }

                stage('Validate outputVar.json file') {

                    agent {
                        docker {
                            image 'python:3-alpine' 
                        }
                    }

                    steps {
                        sh "python -c 'import sys,json; json.load(sys.stdin)' < project/2_DevLab/experiment_rfor/outputVar.json"
                    }

                }

                stage('Validate fileMetadata.json file') {

                    agent {
                        docker {
                            image 'python:3-alpine' 
                        }
                    }

                    steps {
                        sh "python -c 'import sys,json; json.load(sys.stdin)' < project/3_CI_CD/data_quality_test/bad_scenario_demo/fileMetadata.json"
                    }

                }
            }

            post {

                success {
                        echo 'Model MetaData files successfully validated!'
                    }

                failure {
                        echo 'Model MetaData files failed the quality test, please see review them.'
                    }
            }
        }
            // stage('SAS Model Manager Repository service') {
        // }
    }
}