// Jenkinsfile testing test
pipeline {
    agent none
    stages {
        // stage('Build') {
        //     agent {
        //         docker {
        //             image 'python:2-alpine'
        //         }
        //     }
        //     steps {
        //         sh 'python -m py_compile project/2_DevLab/experiment_rfor/score.py'
        //     }
        // }
        stage('Code quality test') {

            agent {
                docker {
                    image 'in92/devops_pylint:v1.3' 
                }
            }

            steps {
                parallel(

                score_code: {
                    sh 'pylint --disable=C project/2_DevLab/experiment_rfor/score.py'
                },
                train_code: {
                    sh 'pylint --disable=C project/2_DevLab/experiment_rfor/train.py'
                }

                )
            }

            post {

                success {
                        echo 'Score and Train code files successfully validated!'
                    }

                failure {
                        echo 'Code failed the quality test, please see logs.'
                    }
            }
        }

        stage('Data Quality Test') {

            agent any

            steps{

                script {
                        try {
                            readJSON file: 'project/2_DevLab/experiment_rfor/fileMetadata.json'
                        } catch (Exception e) {
                            echo "Caught: ${e} JSON not valid!"
                            // currentBuild.result = 'FAILURE'
                        }
                }
            }
        }
    }
}